# Generated by Django 2.0.1 on 2019-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=15)),
                ('leadstatus', models.CharField(max_length=10)),
                ('demodate', models.DateField(blank=True)),
                ('counsler', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
