# Generated by Django 2.0.1 on 2019-11-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completiondate', models.DateField()),
                ('datejoining', models.DateField()),
                ('coursefee', models.IntegerField()),
                ('instructor', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=12)),
                ('customerstatus', models.CharField(default='ongoing', max_length=9)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Register')),
            ],
        ),
    ]
